# This is the project defintion file for mandel.rs

[package]
name = "mandel-rs"
version = "0.1.0"
edition = "2021"
authors = ["Dirk Hillbrecht <dirk@hillbrecht.de>", "Claude AI"]
description = "A fractal graphics visualizer written in Rust, to produce nice graphics and to learn Rust"

[dependencies]
egui = "0.28"
eframe = "0.28"

# end of file
