# This is the project defintion file for mandel.rs

[package]
name = "mandel-rs"
version = "0.1.0"
edition = "2021"
authors = ["Dirk Hillbrecht <dirk@hillbrecht.de>", "Claude AI"]
description = "A fractal graphics visualizer written in Rust, to produce nice graphics and to learn Rust"

[dependencies]
iced = { version = "0.12", features = ["image", "tokio"] }
rand = "0.9.1"
tokio = { version = "1.0", features = ["full"] }

# end of file
